[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'
hook_source='''
    let g:vimtex_compiler_method = 'latexmk'
    let g:vimtex_compiler_latexmk = {'options': []}
    if !exists('g:neocomplete#source#omni#input_patterns')
        let g:neocomplete#source#omni#input_patterns = {}
    endif
    let g:neocomplete#source#omni#input_patterns = g:vimtex#re#neocomplete
    autocmd BufWritePost *.tex VimtexCompileSS
'''

[[plugins]]
repo= 'vim-jp/cpp-vim'
on_ft = ['c', 'cpp']

[[plugins]]
repo='cespare/vim-toml'
on_ft=['toml']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'vim-scripts/gnuplot-syntax-highlighting'
on_ft = 'gnuplot'

